### ISSUE TITLE
[Easy] Add a new rebus

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#103]
This project needs more fun rebuses to solve!

#### Instructions:
Open the file `src/js/rebuses.js` in your favourite editor and add a new rebus object to the end of the rebuses array. Follow [the guide in the readme](https://github.com/ollelauribostrom/rebus#fork-this-repo) for more detailed instructions on how to get started.

**Comment by hi15** [comment]
I will work on it =)
