### ISSUE TITLE
Add autofocus on first char input

### ISSUE THREAD

**Issue by isaniomoraes** [ollelauribostrom/rebus#119]
Would be great if the app autofocused the first char input so users can start typing right away, and fires the autofocus feature on next/prev actions.

Also this can improve the user experience playing only with the keyboard.

![rebus-input-autofocus-suggestion](https://user-images.githubusercontent.com/3224086/47472564-8a258f00-d7e5-11e8-821e-dd13cb058cf5.gif)

**Comment by ollelauribostrom** [comment]
@isaniomoraes Yes! This would be a nice addition. Are you up for a PR?

**Comment by thedavidzhao** [comment]
@ollelauribostrom may I take this if @isaniomoraes hasn't done this already?

**Comment by isaniomoraes** [comment]
@ollelauribostrom nice, thanks!

@thedavidzhao please, go ahead :)
I didn't have a chance to work on this, but I can help testing or something else if you need.
