### ISSUE TITLE
Add section about how to resolve merge conflicts to README

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#145]
To improve the README, we should include a section about how to resolve merge conflicts.

**Comment by kymiddleton** [comment]
Added section in Readme file to outline steps to resolve merge conflicts.

**Comment by andyn95** [comment]
What should I do to fix this? Any files I should look at?

**Comment by kymiddleton** [comment]
@andyn95 I updated the Readme file yesterday and made a pull request to address the issue.  It should be resolved unless the changes are rejected.
