### ISSUE TITLE
Don't autofocus first char input after a rebus has been answered

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#147]
## Expected Behavior
- First char input should not gain focus after a rebus has been answered

## Actual Behavior
- The first char input is focused after a rebus has been answered

## Steps to Reproduce the Problem
1. Answer a rebus
2. The first char input gains focus

**Comment by mrtmrtmlck** [comment]
@ollelauribostrom I'd like to work on this issue. Would it be better displaying the next rebus if the current rebus has been answered correctly ?

**Comment by ollelauribostrom** [comment]
@mrtmrtmlck Awesome! I think it would be best to just focus the "next" button instead 🙂

**Comment by mrtmrtmlck** [comment]
@ollelauribostrom Thank you :) I'll do it like your suggestion 👍
