### ISSUE TITLE
Add first-timers-only badge to README

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#149]
Lets add a `first-timers-only` badge to the README to advertise that those issues exist:

[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)

Add the following markdown next to the other badges in README.md (make sure you add a space between them)
`[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)
`

**Comment by arthurhess** [comment]
I would like to take this.
