### ISSUE TITLE
Add hints

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#153]
As proposed by @wenzelmkay in #67, we could add some kind of hint functionality to the game. This could work something like this:

1. The user enters an incorrect answer n (maybe two/three) times
2. If the rebus has a hint property, display the hint below the input fields

For example, if the rebus data looks like:
```
  {
    symbols: ['Re', '+', '🚌'],
    words: ['Rebus'],
    hint: 'You´re solving one right now'
  },
```
The text `You´re solving one right now` would be displayed after the user has entered an  incorrect answer n times.

**Comment by gizemkeser** [comment]
Hello @ollelauribostrom I would like to work on this issue.

**Comment by ollelauribostrom** [comment]
@gizemkeser Nice, go for it! Let me know if you need any pointers along the way 🙂

**Comment by andyn95** [comment]
Is this issue still open? May I contribute to it? Which file would I have to contribute to in order to work on this?

**Comment by ollelauribostrom** [comment]
@andyn95 This already is being worked on in #168 🙂
