### ISSUE TITLE
Add progress bar to show how many rebuses the player has answered

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#154]
As discussed in #67, we could add a progress bar at the bottom of the window to display how many rebuses the player has answered. This could look something like:

<img width="1273" alt="46904538-cef81e80-cee5-11e8-91bb-6b5d94ab34c4" src="https://user-images.githubusercontent.com/16004130/47951403-8c63b800-df60-11e8-997e-5ff6d2c1decd.png">

Steps:
1. Add a new component (maybe called ProgressBar or something like that)
2. Use the `<progress>` element
3. Connect the component to the store to be able to update it based on how many rebuses that are answered
4. Add/update tests

**Comment by mrtmrtmlck** [comment]
I'd like to work on this issue as my first issue.

**Comment by ollelauribostrom** [comment]
@mrtmrtmlck Nice, go ahead! Let me know if you need any pointers along the way 🙂

**Comment by mrtmrtmlck** [comment]
@ollelauribostrom Thank you! Progress Bar will display like below. Is it OK ?

![image](https://user-images.githubusercontent.com/8123871/47966303-e9936280-e061-11e8-80fd-1acce933b817.png)
