### ISSUE TITLE
Improve the handling of long words

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#155]
When a rebus contains a "long" word, like for instance [this one](https://ollelauribostrom.github.io/rebus/?rebus=6) the input fields will overflow (depending on your screen size ofc). This does not look too pretty in my opinion,

![skarmavbild 2018-11-03 kl 12 33 08 2](https://user-images.githubusercontent.com/16004130/47951704-b5864780-df64-11e8-9de4-0f0250f478f1.png)

Any ideas on how we could improve this?

**Comment by ollelauribostrom** [comment]
@vanwykjd Go for it! What are your thoughts on how to improve this? 🙂

**Comment by andyn95** [comment]
What file would this relate to? Would you like me to contribute to this issue too?

**Comment by vanwykjd** [comment]
@ollelauribostrom I was thinking it would help to have the column widths within the word component be more responsive to the length of the word/words? ...This is my first time attempting to contribute to an OSS, so any pointers will be greatly appreciated!
