### ISSUE TITLE
Answered rebuses in local storage shouldn't have duplicated rebuse id

### ISSUE THREAD

**Issue by mrtmrtmlck** [ollelauribostrom/rebus#163]
## Expected Behavior

Answered rebuses array in local storage should have unique elements

## Actual Behavior

Answered rebuses array in local storage may have duplicated elements

## Steps to Reproduce the Problem

1. Answer a rebus then check answered rebuses in local storage.
2. Come back the answered rebus then remove a char and re-enter it again.
3. Check answered rebuses in local storage again and see the duplicated rebus id.

**Comment by ollelauribostrom** [comment]
I think this should be fixed by #146 right?

**Comment by mrtmrtmlck** [comment]
@ollelauribostrom Yes, you are right! I didn't notice #146 when I opened this one. Now, I'm closing this issue 😊
