### ISSUE TITLE
Rebus links 404

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#172]
#170 made it possible to share a specific rebus based on the url (the url query string is updated each time the user switches to a new rebus). Everything works fine locally but when the site is deployed at https://ollelauribostrom.github.io/rebus/ the url is updated to point to https://ollelauribostrom.github.io/?rebus=2 etc. This will result in a 404 since the /rebus is missing. 

Steps:
- Open the file `components/rebus.js`
- Use`/rebus?rebus=${rebus.id}` when pushing the new state to window.history
- Update the `webpack.config.js` to make this work locally as well, add `historyApiFallback: true` to the devServer configuration.

**Comment by datori** [comment]
Oops, sorry about that.

I'll submit a PR later today 👍
