### ISSUE TITLE
Rename component files using PascalCase

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#177]
We should probably rename the component files using PascalCase to reflect the component names.

- `app.js` -> `App.js`
- `change-button.js`-> `ChangeButton.js`
- `char.js` -> `Char.js`
- `github-corner.js	` -> `GithubCorner.js`
- `hint.js` -> `Hint.js`
- `logo.js` -> `Logo.js`
- `progress-bar.js`-> `ProgressBar.js`
- `rebus.js`-> `Rebus.js`
- `word.js` -> `Word.js`

**Comment by MarcoBomfim** [comment]
On it

**Comment by MarcoBomfim** [comment]
@ollelauribostrom, @vanwykjd, 

Just made the PR. Let me know if there is any other changes required.
