### ISSUE TITLE
Flashing scrollbar after a rebus has been answered correctly

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#179]
When a rebus has been answered correctly and the confetti animation finishes - the scrollbar flashes. 

## Steps to Reproduce the Problem

1. Answer a rebus correctly.
2. Wait until the confetti animation finishes
3. Watch the scrollbar flash for a second

**Comment by vanwykjd** [comment]
After looking into the issue, I found that the content of the `div` containing the confetti animation would sometimes grow larger than the browser window; causing the scrollbar to appear/disappear during the time of the animation. 

I've created PR #186, which includes the adjustment of setting the `overflow` property value to `hidden` of the `.app` class to help address the issue.

**Comment by ollelauribostrom** [comment]
@vanwykjd Nice catch, thanks for fixing this 🙂
