### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#20]
We need to add a code of conduct.

Steps:
- Create a file called `CODE_OF_CONDUCT.md` in the root of the project
- Add the following markdown `This project adheres to the [JS Foundation Code of Conduct](https://js.foundation/community/code-of-conduct).` in `CODE_OF_CONDUCT.md`

**Comment by soulspark666** [comment]
I'll look into it!
