### ISSUE TITLE
Remove invalid CSS property

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#35]
The word class currently contains `justify-items: auto;`. This should be removed since it's an invalid property value. 

Steps:
- Open `src/css/main.css`
- Find the word class
- Remove the line `justify-items: auto;`

**Comment by Ilyeo** [comment]
@ollelauribostrom can I take this one?

**Comment by ollelauribostrom** [comment]
@Ilyeo Sure, go ahead! 🙂

**Comment by Ilyeo** [comment]
@ollelauribostrom done buddy I just opened #37, let know what do you think

**Comment by ollelauribostrom** [comment]
@Ilyeo Thanks again 👍
