### ISSUE TITLE
Fix browser compatibility issues

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#65]
The app currently crashes when loaded in Safari and on older versions of Chrome. To fix these compatibility issues, we have to refactor our babel configuration (in other words, not just target node 10).

**Comment by wallchuck** [comment]
@ollelauribostrom I'm not sure I understood your intensions correctly, but are you saying, that these issues can be solved by just switching Babel's target to, say, `"> 1%, not dead"`?
