### ISSUE TITLE
General UI improvements

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#67]
If you can think of any improvement of the user interface - your contribution is very much welcome. 

The game is live at: https://ollelauribostrom.github.io/rebus/

Some ideas: 
- How to better handle long words?
- How to improve the animations?
- How to improve the mobile UI?

**Comment by ollelauribostrom** [comment]
@zangiboy Yes, that is a good idea. I think that's whats being worked on in #41

**Comment by wenzelmk** [comment]
Here are some ideas:
1. Add a counter for how many the player has gotten correct
2. Add animation for when you've gotten the answer wrong
3. Add hints!

**Comment by ollelauribostrom** [comment]
@wenzelmk Great ideas! 

1. What do you think about a progress bar to show how many rebuses the player has answered? Did some experiments with the `<progress>` element.
![Uploading Skärmavbild 2018-10-13 kl. 12.30.27.png…]()

2. Nice addition. We would probably don't want to run this animation each time the user enters a character - but when the user presses enter (discussed in #72) or when the user has filled out all of them, we could run it. What do you think about some sort of [buzz/shake animation](https://css-tricks.com/snippets/css/shake-css-keyframe-animation/)?

3. Hints would be awesome, maybe we could display the hint after the user has entered an incorrect answer n times 🙂 

Would you like to work on some of this?

**Comment by danoblinux** [comment]
@ollelauribostrom Hi there, I would like to work on some of those improvements.

**Comment by wenzelmkay** [comment]
Hi @ollelauribostrom yes! I am sorry for this late reply. I would like to work on some of these updates to the UI -- what would you like for me to work on? I would be happy to tackle any of those improvements!

**Comment by ollelauribostrom** [comment]
@wenzelmkay and @danoblinux Feel free to work on any of these improvements, just leave a comment below about what you're working on so you don't end up working on the same thing 🙂

**Comment by andyn95** [comment]
What would you like me to do for this issue?

**Comment by ollelauribostrom** [comment]
@andyn95 All of the ideas on how to improve the UI that has been discussed in this issue has already been adressed. If you have any further ideas, feel free to open an issue or submit a pull request with your changes 🙂
