### ISSUE TITLE
Toggle between rebuses using the keyboard

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#69]
To enhance the user experience, we could add the ability to toggle between rebuses using the left/right arrow keys. 

**Steps**:
1. Create a new function called `registerListeners` in `app.js`
2. In the `registerListeners` function, add an event listener that calls `actions.next()` or `actions.prev()` if the user presses the left/right arrow key
3. Call the `registerListeners` function after the `init` function is called [here](https://github.com/ollelauribostrom/rebus/blob/15a8b3db87c338e7c946fda38a43daf630bd5446/src/js/app.js#L32)

**Comment by theonlymikeever** [comment]
I'd like to take a crack at this one, if that's okay

**Comment by ollelauribostrom** [comment]
@theonlymikeever Go ahead, let me know if you need any pointers 🙂

**Comment by theonlymikeever** [comment]
@ollelauribostrom Awesome! I've gone ahead and submitted a PR. Hopefully this is the solution you were aiming for. 

Thoughts for the future -  We could break out listeners into its own file, especially as the app expands. `registerListeners` could take an `event` and `callbackFnc` and do the attachment to the document. After `init()` you could potentially call `registerListeners` through a list of events and callbacks.

**Comment by ollelauribostrom** [comment]
Nice future thoughts and thanks for your PR. I'll add some tests for the `registerListeners` function as well 🙂
