### ISSUE TITLE
Go to next rebus when pressing enter

### ISSUE THREAD

**Issue by gson88** [ollelauribostrom/rebus#72]
It would a better user experience (I think) if user is presented with the next rebus when it presses enter (in any of the input fields)

**Comment by ollelauribostrom** [comment]
@gson88 Do you mean if the user correctly answers a rebus?

**Comment by gson88** [comment]
@ollelauribostrom No, since it's always possible for the user to go to the next rebus by clicking the right arrow element, I think it would make sense for the user to always be able to press enter and go to the next rebus. Like a shortcut to clicking the arrow

**Comment by gson88** [comment]
@ollelauribostrom I noticed now that right/left arrow on the keyboard works to go to the next/prev rebus, didn't know that before sorry. Still think it would make sense to go to next if enter is pressed

**Comment by ollelauribostrom** [comment]
@gson88 I'm thinking that pressing enter (when in a form/input) usually means submitting the form. Maybe we could use the space bar as a shortcut instead? 

So: 
`ArrowRight`: Next rebus
`ArrowLeft`: Previous rebus
`Space`: Skip to next rebus
`Enter`: Check the answer

**Comment by gson88** [comment]
@ollelauribostrom I changed to space in the pull request, merge if you like :) If you decide to merge, can you please add the hacktoberfest label to the issue first?
Enter to check the answer seems unnecessary since it checks the answer each time you write a character. In that case I think it should show some shaking animation to show that it is the wrong answer.
But it's your project and I'm really new to contributing to issues like this so I don't know how it works, really 😄

**Comment by ollelauribostrom** [comment]
@andyn95 This is already being worked on in #81

**Comment by ollelauribostrom** [comment]
Closing this, feel free to reopen 🙂
