### ISSUE TITLE
Add Hint

### ISSUE THREAD

**Issue by bhattabhi013** [ollelauribostrom/rebus#768]
## Expected Behavior
A hint option should be added so the user doesn't stuck.
## Actual Behavior
Not available, new feature.

**Comment by kalebakeits** [comment]
Hints are available however the actual way in which they appear could be improved. It isn't clear what causes hints to appear however for some words they do. I assume having a hint button could solve this

**Comment by GJS2162** [comment]
@bhattabhi013 Hey I want to contribute to this issue. Assign me this and share preferable resources.

**Comment by Prashant7451** [comment]
@kalebakeits hey! let me take this opportunity to fix this problem.

**Comment by Minozzzi** [comment]
Hello everyone! I opened the PR #794 with the changes
