### ISSUE TITLE
In this Redbus top of the right corner having github repository their should be anchor tag indicating github repository.

### ISSUE THREAD

**Issue by Hareesh108** [ollelauribostrom/rebus#805]
## Expected Behavior

...

## Actual Behavior

...

## Steps to Reproduce the Problem

1. Step 1..
2. Step 2..
3. Step 3..

## Specifications

- Browser:

**Comment by JamesHoran** [comment]
It looks like there is an image in the top right corner that one can click on to go to the repo (it also indicates that there is a repo), so this would seems irrelevant or already fixed. What do you think?

**Comment by Hareesh108** [comment]
@JamesHoran  I think it is fixed.
