### ISSUE TITLE
Not Reponsive 

### ISSUE THREAD

**Issue by therealtmmy** [ollelauribostrom/rebus#911]
This is a good project but it's not reponsive to other devices.

**Comment by abhishekDev047** [comment]
can i try something .

**Comment by therealtmmy** [comment]
Yes, you can but the problem is there is no single maintainer for the project. No one to merge pull request.

**Comment by Chetax** [comment]
Sir If It possible Than Find Someone Who Like To Become maintainer for the project Like me.

**Comment by therealtmmy** [comment]
Sadly I am not the owner of this project @Chetax 
I have reached out to the owner himself on linkedin but he is yet to respond to my messages.
I see all of your love and passion for this project. Thank you everyone. Lets hope he comes back to fix this soon.
