### ISSUE TITLE
Save game state in localstorage

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#93]
To improve the playing experience it would be a good idea to save the game state in localStorage. This means saving which rebuses the user has already answered until the next time the user decides to play the game.

Pointers:
- When a user correctly answers a rebus, save the rebus id to localStorage ([starting point](https://github.com/ollelauribostrom/rebus/blob/cc81674c9eeaa00cd12410817933a1b726b1f301/src/js/store.js#L25))
- When getting the rebuses [here](https://github.com/ollelauribostrom/rebus/blob/cc81674c9eeaa00cd12410817933a1b726b1f301/src/js/rebuses.js#L220), check in localStorage if it has already been answered and if so, set `isAnswered: true` and `input: [...Array(rebus.words.join('')]`

**Comment by lgruelas** [comment]
I'm on it.
