### ISSUE TITLE
Get specific rebus from URL query string

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/rebus#94]
If you've added a rebus and you want to challenge a friend to solve it - it would be a nice feature to make it possible to share a specific rebus. In other words, we need to make it possible to start the game at a specific rebus.

Pointers:
- When getting the rebuses [here](https://github.com/ollelauribostrom/rebus/blob/cc81674c9eeaa00cd12410817933a1b726b1f301/src/js/rebuses.js#L220) use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to find out if the user passed a query string
- If the user passed a query string like `?rebus=12`, put the  rebus with the id of 12 first in the array that is returned from `getRebuses`

**Comment by tkilgour** [comment]
I'd love to take a crack at this! This looks like a great project.
